// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/ai-analytics" | "/ai-control" | "/ai-voice" | "/bookings" | "/dashboard" | "/documents" | "/employee-performance-analysis" | "/employees" | "/hni-clients" | "/leads" | "/leads/[id]" | "/login" | "/meta-ads" | "/properties" | "/reports" | "/scripts" | "/settings" | "/site-visits" | "/smart-matching" | "/trash" | "/whatsapp"
type AppRouteHandlerRoutes = "/api/admin/users" | "/api/ai-voice/[...path]" | "/api/auth/change-password" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/me" | "/api/auth/profile" | "/api/bookings" | "/api/bookings/[id]" | "/api/clients/[id]" | "/api/clients/[id]/status" | "/api/dashboard/ai-analytics/[...path]" | "/api/dashboard/employee-performance" | "/api/employees" | "/api/hni" | "/api/hni/[id]" | "/api/hni/[id]/activities" | "/api/import/meta-leads" | "/api/import/template/meta-leads" | "/api/leads/meta" | "/api/leads/meta/[id]" | "/api/leads/meta/[id]/assign" | "/api/leads/meta/[id]/crm" | "/api/leads/meta/[id]/detail" | "/api/leads/meta/[id]/property-recommendations" | "/api/leads/meta/[id]/unassign" | "/api/leads/meta/assign-bulk" | "/api/properties" | "/api/properties/[id]" | "/api/site-visits" | "/api/site-visits/[id]" | "/api/webhooks/meta"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/ai-analytics": {}
  "/ai-control": {}
  "/ai-voice": {}
  "/api/admin/users": {}
  "/api/ai-voice/[...path]": { "path": string[]; }
  "/api/auth/change-password": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/auth/profile": {}
  "/api/bookings": {}
  "/api/bookings/[id]": { "id": string; }
  "/api/clients/[id]": { "id": string; }
  "/api/clients/[id]/status": { "id": string; }
  "/api/dashboard/ai-analytics/[...path]": { "path": string[]; }
  "/api/dashboard/employee-performance": {}
  "/api/employees": {}
  "/api/hni": {}
  "/api/hni/[id]": { "id": string; }
  "/api/hni/[id]/activities": { "id": string; }
  "/api/import/meta-leads": {}
  "/api/import/template/meta-leads": {}
  "/api/leads/meta": {}
  "/api/leads/meta/[id]": { "id": string; }
  "/api/leads/meta/[id]/assign": { "id": string; }
  "/api/leads/meta/[id]/crm": { "id": string; }
  "/api/leads/meta/[id]/detail": { "id": string; }
  "/api/leads/meta/[id]/property-recommendations": { "id": string; }
  "/api/leads/meta/[id]/unassign": { "id": string; }
  "/api/leads/meta/assign-bulk": {}
  "/api/properties": {}
  "/api/properties/[id]": { "id": string; }
  "/api/site-visits": {}
  "/api/site-visits/[id]": { "id": string; }
  "/api/webhooks/meta": {}
  "/bookings": {}
  "/dashboard": {}
  "/documents": {}
  "/employee-performance-analysis": {}
  "/employees": {}
  "/hni-clients": {}
  "/leads": {}
  "/leads/[id]": { "id": string; }
  "/login": {}
  "/meta-ads": {}
  "/properties": {}
  "/reports": {}
  "/scripts": {}
  "/settings": {}
  "/site-visits": {}
  "/smart-matching": {}
  "/trash": {}
  "/whatsapp": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
