// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/ai-analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-analytics">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/ai-analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/ai-control/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-control">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/ai-control/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/ai-voice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-voice">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/ai-voice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/bookings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bookings">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/bookings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/documents">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/employee-performance-analysis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employee-performance-analysis">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/employee-performance-analysis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/employees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employees">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/employees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/hni-clients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hni-clients">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/hni-clients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/leads/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leads/[id]">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/leads/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leads">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/meta-ads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/meta-ads">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/meta-ads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/properties/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/properties">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/properties/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/scripts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/scripts">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/scripts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/site-visits/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/site-visits">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/site-visits/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/smart-matching/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/smart-matching">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/smart-matching/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/trash/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trash">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/trash/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/whatsapp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/whatsapp">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/whatsapp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ai-voice/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-voice/[...path]">> = Specific
  const handler = {} as typeof import("../../../app/api/ai-voice/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/change-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/change-password">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/change-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/profile">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/bookings/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookings/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/bookings/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/bookings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookings">> = Specific
  const handler = {} as typeof import("../../../app/api/bookings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/clients/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clients/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/clients/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/clients/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clients/[id]/status">> = Specific
  const handler = {} as typeof import("../../../app/api/clients/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/dashboard/ai-analytics/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/ai-analytics/[...path]">> = Specific
  const handler = {} as typeof import("../../../app/api/dashboard/ai-analytics/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/dashboard/employee-performance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/employee-performance">> = Specific
  const handler = {} as typeof import("../../../app/api/dashboard/employee-performance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/employees/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/employees">> = Specific
  const handler = {} as typeof import("../../../app/api/employees/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/hni/[id]/activities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hni/[id]/activities">> = Specific
  const handler = {} as typeof import("../../../app/api/hni/[id]/activities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/hni/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hni/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/hni/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/hni/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hni">> = Specific
  const handler = {} as typeof import("../../../app/api/hni/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/import/meta-leads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import/meta-leads">> = Specific
  const handler = {} as typeof import("../../../app/api/import/meta-leads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/import/template/meta-leads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import/template/meta-leads">> = Specific
  const handler = {} as typeof import("../../../app/api/import/template/meta-leads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/leads/meta/[id]/assign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/meta/[id]/assign">> = Specific
  const handler = {} as typeof import("../../../app/api/leads/meta/[id]/assign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/leads/meta/[id]/crm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/meta/[id]/crm">> = Specific
  const handler = {} as typeof import("../../../app/api/leads/meta/[id]/crm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/leads/meta/[id]/detail/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/meta/[id]/detail">> = Specific
  const handler = {} as typeof import("../../../app/api/leads/meta/[id]/detail/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/leads/meta/[id]/property-recommendations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/meta/[id]/property-recommendations">> = Specific
  const handler = {} as typeof import("../../../app/api/leads/meta/[id]/property-recommendations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/leads/meta/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/meta/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/leads/meta/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/leads/meta/[id]/unassign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/meta/[id]/unassign">> = Specific
  const handler = {} as typeof import("../../../app/api/leads/meta/[id]/unassign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/leads/meta/assign-bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/meta/assign-bulk">> = Specific
  const handler = {} as typeof import("../../../app/api/leads/meta/assign-bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/leads/meta/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/meta">> = Specific
  const handler = {} as typeof import("../../../app/api/leads/meta/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/properties/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/properties/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/properties/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/properties/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/properties">> = Specific
  const handler = {} as typeof import("../../../app/api/properties/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/site-visits/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/site-visits/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/site-visits/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/site-visits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/site-visits">> = Specific
  const handler = {} as typeof import("../../../app/api/site-visits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/webhooks/meta/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/meta">> = Specific
  const handler = {} as typeof import("../../../app/api/webhooks/meta/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
